[patch]
title = "洛克人EXE3 黑版BLX 中文化"
authors = ["NW洛克人爱好者&flyeyes汉化组 <593002516@qq.com>"]

[versions.'1.3.0']
netplay_compatibility = "bn3"

[versions.'1.3.1']
netplay_compatibility = "bn3"

[versions.'1.4.0']
netplay_compatibility = "bn3"
