[patch]
title = "40 Chip Folders (BN6 Falzar)"
authors = [
    "luckytyphlosion <10688458+luckytyphlosion@users.noreply.github.com>"
]
source = "https://github.com/luckytyphlosion/bn6-40-chips"
license = "MIT"
for_rom = "MEGAMAN6_FXXBR6E"

[versions.'1.1.0']
netplay_compatibility = "bn640chips"