[patch]
title = "idealexe English (EXE6 Falzar)"
authors = [
    "idealexe <omega_8810@yahoo.co.jp>",
    "exeguy11 <exeguy11@[100::]>",
    "ssbmars <46971717+ssbmars@users.noreply.github.com>",
]
source = "https://github.com/ssbmars/ideal_EXE6_patch"
for_rom = "ROCKEXE6_RXXBR6J"

[versions.'1.0.0']
netplay_compatibility = "exe6"
