[patch]
title = "All-Stars (BN6 Gregar)"
authors = [
    "luckytyphlosion <10688458+luckytyphlosion@users.noreply.github.com>",
]
source = "https://github.com/luckytyphlosion/bn6-all-stars"
license = "MIT"
for_rom = "MEGAMAN6_GXX"

[versions.'1.0.0']
netplay_compatibility = "bn6allstars"
