[patch]
title = "SoundMod (BN6 Gregar)"
authors = ["idealexe <omega_8810@yahoo.co.jp>"]
source = "https://github.com/idealexe/EXE6_Tools"
for_rom = "MEGAMAN6_GXX"

[[versions.'0.0.0']]
netplay_compatibility = "bn6-allstars"
