[patch]
title = "シリーズ音源&曲追加（EXE6 ファルザー）"
authors = ["idealexe <omega_8810@yahoo.co.jp>"]
source = "https://github.com/idealexe/EXE6_Tools"
for_rom = "ROCKEXE6_RXX"

[[versions.'0.0.0']]
netplay_compatibility = "exe6"
